/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ybits_pms_common_nfi_NativeProxy */

#ifndef _Included_cn_ybits_pms_common_nfi_NativeProxy
#define _Included_cn_ybits_pms_common_nfi_NativeProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ybits_pms_common_nfi_NativeProxy
 * Method:    welcomeMessage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_ybits_pms_common_nfi_NativeProxy_welcomeMessage
  (JNIEnv *, jclass);

/*
 * Class:     cn_ybits_pms_common_nfi_NativeProxy
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_ybits_pms_common_nfi_NativeProxy_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ybits_pms_common_nfi_NativeProxy
 * Method:    calcCost
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_cn_ybits_pms_common_nfi_NativeProxy_calcCost
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     cn_ybits_pms_common_nfi_NativeProxy
 * Method:    mailSecurityInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_ybits_pms_common_nfi_NativeProxy_mailSecurityInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
